// THIS FILE IS GENERATED AUTOMATICALLY
#include <qtils/append.hpp>
#include <qtils/assert.hpp>
#include <qtils/bitspan.hpp>
#include <qtils/byte_utils.hpp>
#include <qtils/bytes.hpp>
#include <qtils/bytes_std_hash.hpp>
#include <qtils/bytestr.hpp>
#include <qtils/create_smart_pointer_macros.hpp>
#include <qtils/cxx20/lexicographical_compare_three_way.hpp>
#include <qtils/cxx23/forward_like.hpp>
#include <qtils/cxx23/print.hpp>
#include <qtils/cxx23/ranges/contains.hpp>
#include <qtils/empty.hpp>
#include <qtils/enum_error_code.hpp>
#include <qtils/error.hpp>
#include <qtils/final_action.hpp>
#include <qtils/fixed_byte_vector.hpp>
#include <qtils/hex.hpp>
#include <qtils/macro/common.hpp>
#include <qtils/macro/unwrap.hpp>
#include <qtils/option_take.hpp>
#include <qtils/optional_ref.hpp>
#include <qtils/outcome.hpp>
#include <qtils/read_file.hpp>
#include <qtils/shared_ref.hpp>
#include <qtils/tagged.hpp>
#include <qtils/test/outcome.hpp>
#include <qtils/unhex.hpp>
#include <qtils/unused.hpp>
int main(){}
